# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           c2goasm
%define go_import_path  github.com/minio/c2goasm
# Upstream does not provide git tags, use commit ID instead - 251
%define commit_id 36a3d3bbc4f3ec1eafcf7989776be7e84736ace9
# TODO: Fix this shit, or not - 251
%define go_test_exclude github.com/minio/c2goasm/cgocmp
# TODO: c2goasm's test uses amd64 SIMD (AVX) only - 251
%define go_test_ignore_failure 1

Name:           go-github-minio-c2goasm
Version:        0+git20260108.36a3d3b
Release:        %autorelease
Summary:        C to Go Assembly
License:        Apache-2.0
URL:            https://github.com/minio/c2goasm
#!RemoteAsset
Source0:        https://github.com/minio/c2goasm/archive/%{commit_id}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n %{_name}-%{commit_id}
BuildOption(check):  -vet=off

BuildRequires:  go
BuildRequires:  go-rpm-macros

Provides:       go(github.com/minio/c2goasm) = %{version}

%description
This is a tool to convert assembly as generated by a C/C++ compiler into
Golang assembly. It is meant to be used in combination with asm2plan9s
(https://github.com/minio/asm2plan9s) in order to automatically generate
pure Go wrappers for C/C++ code (that may for instance take advantage of
compiler SIMD intrinsics or template<> code).

%files
%license LICENSE*
%doc README*
%{go_sys_gopath}/%{go_import_path}

%changelog
%{?autochangelog}
